services:
  - type: web
    name: facebook-video-player-api
    env: node
    buildCommand: pip install yt-dlp && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
