services:
  - type: web
    name: facebook-video-player-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: YTDLP_PATH
        value: /tmp/yt-dlp
    plan: free
